"""Add section_index to risks

Revision ID: 1d6aa4f2962e
Revises: a76644c11c32
Create Date: 2026-03-04 15:48:55.605309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d6aa4f2962e'
down_revision: Union[str, None] = 'a76644c11c32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('risks', sa.Column('section_index', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('risks', 'section_index')
    # ### end Alembic commands ###
