"""add_use_law_analysis_to_contracts

Revision ID: 41985ad81641
Revises: 0001_template_feature
Create Date: 2026-02-26 09:15:58.431471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41985ad81641'
down_revision: Union[str, None] = '0001_template_feature'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column('use_law_analysis', sa.Boolean(), nullable=True))
    op.add_column('risks', sa.Column('risk_source', sa.String(), nullable=True))
    op.create_index(op.f('ix_risks_risk_source'), 'risks', ['risk_source'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_risks_risk_source'), table_name='risks')
    op.drop_column('risks', 'risk_source')
    op.drop_column('contracts', 'use_law_analysis')
    # ### end Alembic commands ###
