"""Add htmlPreview to ContractType

Revision ID: a76644c11c32
Revises: 41985ad81641
Create Date: 2026-03-04 14:37:17.946311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a76644c11c32'
down_revision: Union[str, None] = '41985ad81641'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Use IF NOT EXISTS so migration is idempotent
    op.execute('ALTER TABLE contracts ALTER COLUMN "sectionPairsJson" TYPE JSON USING "sectionPairsJson"::JSON')
    op.execute('ALTER TABLE contract_types ADD COLUMN IF NOT EXISTS "templateUrl" VARCHAR')
    op.execute('ALTER TABLE contract_types ADD COLUMN IF NOT EXISTS htmlpreview TEXT')


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contract_types', 'htmlpreview')
    op.drop_column('contract_types', 'templateUrl')
    op.alter_column('contracts', 'sectionPairsJson',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    # ### end Alembic commands ###
